name: Test the action

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest
          - name: Android32
            os: ubuntu-latest
            target: Android32
          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout textureldr
        uses: actions/checkout@v4
        with:
          repository: geode-sdk/textureldr
          path: textureldr

      - name: Build the mod
        uses: ./
        with:
          # sdk: nightly
          build-config: RelWithDebInfo
          path: textureldr
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package Both Builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Combine builds
        uses: ./combine
        id: build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
